# Name of workflow
name: CI

# Trigger the workflow on push or pull request
on:
  - push
  - pull_request

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: npm install, build
        # Install and build project
        run: |
          make install
          make build
        # Add environment variables
        env:
          CI: true

      - name: Run linter
        run: make lint

