---
env:
  browser: true
  
extends:
  - airbnb-base
  - "plugin:functional/external-recommended"
  - "plugin:functional/recommended"

parser: babel-eslint

parserOptions:
  ecmaVersion: 2020

rules:
  import/extensions: 0
  react/prop-types: 0
  no-console: 0
  no-await-in-loop: 0
